/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://analogjs.org/license
 */

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import {
  generateRouteTree,
  generateRouteTreeFile,
  normalizeDiscoveredRoutes,
  type DiscoveredRoute,
} from '../../src/lib/generator/route-tree-generator';

describe('Route Tree Generator for Type-Safe Routing', () => {
  // --------------------------------------------------------------------------
  // 1. Route Sorting & Normalization
  // --------------------------------------------------------------------------
  describe('normalizeDiscoveredRoutes & sortDiscoveredRoutes', () => {
    it('should deterministically sort routes: root, parents before children, index before dynamic, static before param', () => {
      const routes: DiscoveredRoute[] = [
        { id: '/blog/[...slug]' },
        { id: '/blog/intro' },
        { id: '/blog/[category]' },
        { id: '/users/[userId]' },
        { id: '/users' },
        { id: '/users/index', isIndex: true },
        { id: '/about' },
        { id: '/' },
        { id: '/users/[userId]/settings' },
      ];

      const sorted = normalizeDiscoveredRoutes(routes);
      const sortedIds = sorted.map((r) => r.id);

      // Root route must be first
      expect(sortedIds[0]).toBe('/');
      // Static routes before dynamic routes
      expect(sortedIds.indexOf('/about')).toBeLessThan(
        sortedIds.indexOf('/users/[userId]'),
      );
      // Parent /users before child /users/[userId]
      expect(sortedIds.indexOf('/users')).toBeLessThan(
        sortedIds.indexOf('/users/[userId]'),
      );
      // Index /users/ before param /users/[userId]
      expect(sortedIds.indexOf('/users/')).toBeLessThan(
        sortedIds.indexOf('/users/[userId]'),
      );
      // Parent /users/[userId] before nested /users/[userId]/settings
      expect(sortedIds.indexOf('/users/[userId]')).toBeLessThan(
        sortedIds.indexOf('/users/[userId]/settings'),
      );
      // Sibling sorting: static before param, param before wildcard
      expect(sortedIds.indexOf('/blog/intro')).toBeLessThan(
        sortedIds.indexOf('/blog/[category]'),
      );
      expect(sortedIds.indexOf('/blog/[category]')).toBeLessThan(
        sortedIds.indexOf('/blog/[...slug]'),
      );
    });
  });

  // --------------------------------------------------------------------------
  // 2. TypeScript Declaration Generation (generateRouteTree)
  // --------------------------------------------------------------------------
  describe('generateRouteTree Type Declarations', () => {
    it('should emit clean, valid declaration merging TypeScript definitions', () => {
      const routes: DiscoveredRoute[] = [
        {
          id: '/',
          path: '/',
          fullPath: '/',
        },
        {
          id: '/users',
          path: 'users',
          fullPath: '/users',
        },
        {
          id: '/users/:userId',
          path: ':userId',
          fullPath: '/users/:userId',
        },
      ];

      const generated = generateRouteTree(routes);

      // Verify banner
      expect(generated).toContain(
        'This file was automatically generated by Analog Router',
      );

      // Verify declaration merging augmentation
      expect(generated).toContain(`declare module '@analogjs/router' {`);
      expect(generated).toContain(`interface FileRoutesByPath {`);
      expect(generated).toContain(`'/': {`);
      expect(generated).toContain(`'/users': {`);
      expect(generated).toContain(`'/users/:userId': {`);
      expect(generated).toContain(`id: '/users/:userId';`);
      expect(generated).toContain(`path: ':userId';`);
      expect(generated).toContain(`fullPath: '/users/:userId';`);

      expect(generated).toContain(`interface Register {`);
      expect(generated).toContain(`navigationMap: FileRoutesByFullPath;`);

      // Verify type exports
      expect(generated).toContain(`export type FileRoutesByFullPath = {`);
      expect(generated).toContain(
        `'/users/:userId': FileRoutesByPath['/users/:userId'];`,
      );
    });
  });

  // --------------------------------------------------------------------------
  // 3. Disk Operations & Idempotency (generateRouteTreeFile)
  // --------------------------------------------------------------------------
  describe('generateRouteTreeFile Disk Operations', () => {
    let tempDir: string;

    beforeEach(async () => {
      tempDir = await fs.promises.mkdtemp(
        path.join(os.tmpdir(), 'analog-routes-test-'),
      );
    });

    afterEach(async () => {
      if (tempDir && fs.existsSync(tempDir)) {
        await fs.promises.rm(tempDir, { recursive: true, force: true });
      }
    });

    it('should discover pages and generate routeTree.gen.ts with idempotency check', async () => {
      const routesDir = path.join(tempDir, 'src/app/pages');
      const generatedPath = path.join(tempDir, 'src/routeTree.gen.ts');

      await fs.promises.mkdir(routesDir, { recursive: true });
      await fs.promises.writeFile(
        path.join(routesDir, 'index.page.ts'),
        `export default class Index {}`,
      );
      await fs.promises.mkdir(path.join(routesDir, 'users'), {
        recursive: true,
      });
      await fs.promises.writeFile(
        path.join(routesDir, 'users.page.ts'),
        `export default class Users {}`,
      );
      await fs.promises.writeFile(
        path.join(routesDir, 'users/[id].page.ts'),
        `export default class UserDetail {}`,
      );
      // Dot-notation route
      await fs.promises.writeFile(
        path.join(routesDir, 'products.[productId].page.ts'),
        `export default class ProductDetail {}`,
      );
      // Route group
      await fs.promises.mkdir(path.join(routesDir, '(auth)'), {
        recursive: true,
      });
      await fs.promises.writeFile(
        path.join(routesDir, '(auth)/login.page.ts'),
        `export default class Login {}`,
      );

      // First run: should create file and return changed: true
      const run1 = await generateRouteTreeFile({ routesDir, generatedPath });
      expect(run1.changed).toBe(true);
      expect(fs.existsSync(generatedPath)).toBe(true);

      const content1 = await fs.promises.readFile(generatedPath, 'utf8');
      expect(content1).toContain(`'/': {`);
      expect(content1).toContain(`'/users': {`);
      expect(content1).toContain(`'/users/[id]': {`);
      expect(content1).toContain(
        `'/users/:id': FileRoutesByPath['/users/[id]'];`,
      );
      // Dot-notation route maps to '/products/:productId'
      expect(content1).toContain(
        `'/products/:productId': FileRoutesByPath['/products/[productId]'];`,
      );
      // Route group maps to '/login'
      expect(content1).toContain(
        `'/login': FileRoutesByPath['/(auth)/login'];`,
      );

      // Second run without modifications: should return changed: false
      const run2 = await generateRouteTreeFile({ routesDir, generatedPath });
      expect(run2.changed).toBe(false);
      expect(run2.content).toBe(content1);
    });
  });
});
