/* eslint-disable */
/* prettier-ignore */
// Generated by @analogjs/router

import '@analogjs/router';

declare module '@analogjs/router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      types?: {
        data?: { title: string; section: string };
      };
    };
    '/users': {
      id: '/users';
      path: '/users';
      fullPath: '/users';
    };
    '/users/:userId': {
      id: '/users/:userId';
      path: '/users/:userId';
      fullPath: '/users/:userId';
      types?: {
        params?: { userId: string };
        queryParams?: { tab?: 'info' | 'activity'; highlight?: boolean };
        data?: { title: string; section: string };
      };
    };
    '/users/:userId/posts/:postId': {
      id: '/users/:userId/posts/:postId';
      path: '/users/:userId/posts/:postId';
      fullPath: '/users/:userId/posts/:postId';
      types?: {
        params?: { userId: string; postId: string };
        queryParams?: { edit?: boolean };
      };
    };
    '/search': {
      id: '/search';
      path: '/search';
      fullPath: '/search';
      types?: {
        queryParams?: {
          q?: string;
          page?: number;
          sort?: 'asc' | 'desc' | 'relevance';
          inStock?: boolean;
          categories?: string[];
        };
      };
    };
    '/docs/**': {
      id: '/docs/**';
      path: '/docs/**';
      fullPath: '/docs/**';
      types?: {
        params?: { '**': string; slug?: string };
      };
    };
    '/admin': {
      id: '/admin';
      path: '/admin';
      fullPath: '/admin';
      types?: {
        data?: { section: string; title: string; requiresAuth: boolean };
      };
    };
    '/admin/dashboard': {
      id: '/admin/dashboard';
      path: '/admin/dashboard';
      fullPath: '/admin/dashboard';
      types?: {
        data?: { title: string; metricsEnabled: boolean };
      };
    };
    '/admin/users': {
      id: '/admin/users';
      path: '/admin/users';
      fullPath: '/admin/users';
    };
    '/admin/settings': {
      id: '/admin/settings';
      path: '/admin/settings';
      fullPath: '/admin/settings';
      types?: {
        data?: { requiresAdmin: boolean; role: 'superadmin' | 'editor' };
      };
    };
    '/orgs/:orgId/teams/:teamId/members/:memberId': {
      id: '/orgs/:orgId/teams/:teamId/members/:memberId';
      path: '/orgs/:orgId/teams/:teamId/members/:memberId';
      fullPath: '/orgs/:orgId/teams/:teamId/members/:memberId';
      types?: {
        params?: { orgId: string; teamId: string; memberId: string };
        queryParams?: { view?: 'compact' | 'expanded'; highlighted?: boolean };
        data?: { role: string; level: number };
      };
    };
  }
}
